"""
ACT-style Transformer Encoder/Decoder used in Exp 2, 3, 6, 7, 8, 9.

Implements action chunking: instead of predicting one action per frame,
the model predicts a sequence of chunk_size future actions at once.
This produces smoother, more temporally consistent driving behaviour.

Input:  CNN feature vector  (B, cnn_dim)          — "what does the camera see?"
Output: action logit chunk  (B, chunk_size, 4)     — "what to do for next N steps"

# ---------------------------------------------------------------------------
# WHAT PROBLEM DOES THIS SOLVE?
# ---------------------------------------------------------------------------
# In Exp 1 the model predicts one action per image frame, independently.
# Because each prediction is made without awareness of the previous or next
# decision, the car can flip-flop: left → right → left → right, producing
# jerky, unstable driving.
#
# Action Chunking (from the ACT paper — Action Chunking with Transformers):
# Predict chunk_size future actions all at once. The car executes the full
# chunk before asking again. A sequence "go left for 5 steps" is internally
# consistent — the model can't produce alternating left/right because the
# entire sequence is generated by one coherent forward pass.
#
# Experiment results confirm this: adding the Transformer improves accuracy
# from 90% (Exp 1, CNN+MLP) to 92.4% (Exp 2, CNN+Transformer).

# ---------------------------------------------------------------------------
# KEY CONCEPTS YOU WILL LEARN HERE
# ---------------------------------------------------------------------------
# ── CONCEPT 1: SELF-ATTENTION ─────────────────────────────────────────────
# Every token in a sequence can "look at" every other token to gather context.
#
# Concrete example: B=2 samples, T=1 token, D=8 features
#
#   input: (2, 1, 8)
#
#   Three linear projections produce Q, K, V:
#     Q = input @ W_Q    # (2, 1, 8) @ (8, 8) → (2, 1, 8)
#     K = input @ W_K    # (2, 1, 8) @ (8, 8) → (2, 1, 8)
#     V = input @ W_V    # (2, 1, 8) @ (8, 8) → (2, 1, 8)
#
#   Attention score — how much should token i attend to token j?
#     scores  = Q @ K.transpose(-1, -2) / sqrt(D)   # (2, 1, 1)
#     weights = softmax(scores, dim=-1)              # (2, 1, 1)  rows sum to 1
#     output  = weights @ V                          # (2, 1, 8)
#
#   Shape rule for @ (batch matmul):
#     Only the LAST TWO dims multiply. All earlier dims are batch dims.
#     (2, 1, 8) @ (2, 8, 1) → (2, 1, 1)   ← T×D times D×T gives T×T scores
#     (2, 1, 1) @ (2, 1, 8) → (2, 1, 8)   ← T×T times T×D gives T×D output
#
# ── CONCEPT 2: WHY DIVIDE BY sqrt(D)? ────────────────────────────────────
# Q @ K^T produces values whose magnitude grows with D (the feature size).
# If D=64, a single dot product can be a sum of 64 terms — easily ±50.
# Softmax of large values becomes nearly one-hot (extreme), which kills
# gradient flow. Dividing by sqrt(D) keeps the scores in a moderate range
# so softmax stays soft and gradients flow evenly.
#
# ── CONCEPT 3: MULTI-HEAD ATTENTION ──────────────────────────────────────
# Instead of one big Q/K/V projection in D-dim space, split into h heads
# each working in (D/h)-dim space, run attention independently per head,
# then concatenate the results:
#
#   (B, T, D) → reshape → (B, h, T, D/h)   ← split into h heads
#   → attention per head → (B, h, T, D/h)
#   → reshape back      → (B, T, D)         ← heads concatenated
#   → linear projection → (B, T, D)
#
# Why h heads? Each head can specialise on different aspects of the input.
# One head might track "which direction am I going", another "how close
# is the road edge". The concatenation then has D total numbers covering
# many learned perspectives simultaneously.
#
# PyTorch's nn.MultiheadAttention handles all this internally.
#
# ── CONCEPT 4: CROSS-ATTENTION (in the decoder) ───────────────────────────
# Same as self-attention but Q and K/V come from DIFFERENT sequences:
#   Q:  (B, chunk_size, D)  ← decoder query tokens — "what do I do at step k?"
#   K:  (B, T, D)           ← encoder output — "what does the image say?"
#   V:  (B, T, D)           ← encoder output
#
#   scores = Q @ K^T → (B, chunk_size, T)   ← each query attends to all T tokens
#   output = scores @ V → (B, chunk_size, D) ← each step collects weighted info
#
# Each of the chunk_size query slots asks: "given what the encoder knows,
# what is relevant for MY time step?" The decoder produces one output
# vector per future action step.
#
# ── CONCEPT 5: POSITIONAL ENCODING ───────────────────────────────────────
# Attention has no built-in sense of order — it treats its input as a SET,
# not a SEQUENCE. Two tokens at positions 1 and 5 look identical unless we
# tell the model their positions.
#
# We add a positional encoding to each token before feeding into attention:
#   token at position p → token + PE[p]
#
# The encoding uses alternating sine and cosine waves of different frequencies:
#   PE[p, 2i]   = sin(p / 10000^(2i/D))
#   PE[p, 2i+1] = cos(p / 10000^(2i/D))
#
# Why sinusoids? They are bounded (−1 to 1), periodic, and — crucially —
# the model can easily learn relative positions because sin/cos of sums
# decompose predictably. Each dimension oscillates at a different frequency
# so every position gets a unique fingerprint across all D dimensions.
#
# ── CONCEPT 6: FEED-FORWARD SUBLAYER ─────────────────────────────────────
# After each attention block, a two-layer MLP (Linear → ReLU → Linear)
# is applied to EACH token independently. This is where the model does
# per-token computation — attention gathers context, the MLP processes it.
# The hidden dim is typically 4× the model dim (so d_model=64 → ff_dim=256).
#
# ── CONCEPT 7: RESIDUAL CONNECTIONS + LAYER NORM ─────────────────────────
# After each sublayer (attention or MLP):
#   output = LayerNorm(x + sublayer(x))
# The "+x" is the residual (skip) connection. It lets gradients flow
# directly through the network without passing through attention/MLP,
# preventing vanishing gradients in deep stacks.
# LayerNorm normalises each token vector to zero mean / unit variance,
# stabilising training.

# ---------------------------------------------------------------------------
# STRUCTURE
# ---------------------------------------------------------------------------
#   PositionalEncoding
#     forward(x)  — adds sinusoidal PE to (B, T, D) input
#
#   ACTTransformer
#     __init__(cnn_dim, d_model, nhead, num_enc_layers, num_dec_layers,
#              ff_dim, chunk_size, num_actions, dropout)
#     forward(cnn_features)  — (B, cnn_dim) → (B, chunk_size, num_actions)
#
#   Internal flow:
#     cnn_features (B, cnn_dim)
#     → input_proj  → (B, 1, d_model)       ← single encoder token
#     → PositionalEncoding
#     → TransformerEncoder (self-attention)  → (B, 1, d_model)
#     → TransformerDecoder (cross-attention) ← query_embed (chunk_size, d_model)
#     → (B, chunk_size, d_model)
#     → action_head → (B, chunk_size, num_actions)

# ---------------------------------------------------------------------------
# USAGE
# ---------------------------------------------------------------------------
#   from shared.models.transformer import ACTTransformer
#
#   model = ACTTransformer(
#       cnn_dim=64,       # CNN backbone output size
#       d_model=64,       # transformer internal dimension
#       nhead=4,          # number of attention heads (d_model must be divisible)
#       num_enc_layers=2, # encoder depth
#       num_dec_layers=2, # decoder depth
#       ff_dim=256,       # feed-forward hidden dim
#       chunk_size=10,    # how many future action steps to predict
#       num_actions=4,    # forward/backward/left/right
#   )
#
#   import torch
#   cnn_feats = torch.randn(8, 64)               # batch of 8, 64-dim CNN output
#   logits = model(cnn_feats)                    # (8, 10, 4)
#   # logits[b, t, a] = raw score for action a at future step t in sample b
"""

from __future__ import annotations

import math

import torch
import torch.nn as nn


# ---------------------------------------------------------------------------
# Positional Encoding
# ---------------------------------------------------------------------------

class PositionalEncoding(nn.Module):
    """Adds sinusoidal positional encoding to a sequence of token embeddings.

    Parameters
    ----------
    d_model  : dimension of each token embedding (must match transformer d_model)
    max_len  : maximum sequence length supported (safe to set well above actual use)
    dropout  : dropout applied after adding positional encoding
    """

    def __init__(self, d_model: int, max_len: int = 512, dropout: float = 0.1) -> None:
        super().__init__()

        # Dropout is applied after adding positional encoding — mild regularisation.
        self.dropout = nn.Dropout(p=dropout)

        # Build the positional encoding matrix: shape (max_len, d_model)
        # pe[p, i] = sin or cos of a sinusoid whose frequency depends on i.
        pe = torch.zeros(max_len, d_model)   # (max_len, d_model)

        # position vector: [0, 1, 2, ..., max_len-1], shape (max_len, 1)
        # unsqueeze(1) adds the second dim so broadcasting works below.
        position = torch.arange(0, max_len).unsqueeze(1).float()   # (max_len, 1)

        # div_term[i] = 1 / 10000^(2i/d_model)
        # Shape: (d_model // 2,)
        # We use log-space arithmetic for numerical stability:
        #   10000^(2i/d_model) = exp(2i * ln(10000) / d_model)
        # so 1/that = exp(-2i * ln(10000) / d_model)
        div_term = torch.exp(
            torch.arange(0, d_model, 2).float()   # [0, 2, 4, ..., d_model-2]
            * (-math.log(10000.0) / d_model)
        )  # (d_model // 2,)

        # Even indices (0, 2, 4, ...) get sine encoding
        # pe[:, 0::2] selects columns 0, 2, 4, ... → shape (max_len, d_model//2)
        # position * div_term broadcasts: (max_len, 1) * (d_model//2,) → (max_len, d_model//2)
        pe[:, 0::2] = torch.sin(position * div_term)   # (max_len, d_model//2)

        # Odd indices (1, 3, 5, ...) get cosine encoding
        pe[:, 1::2] = torch.cos(position * div_term)   # (max_len, d_model//2)

        # register_buffer stores pe as part of the module state (saved/loaded
        # with the model) but marks it as NOT a learnable parameter.
        # It moves to the correct device automatically with model.to(device).
        # unsqueeze(0) adds batch dim → (1, max_len, d_model)
        # so we can broadcast over the batch dimension in forward().
        self.register_buffer("pe", pe.unsqueeze(0))   # (1, max_len, d_model)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # x shape: (B, T, d_model)
        # self.pe[:, :T, :] selects the first T positions → (1, T, d_model)
        # Adding (B, T, d_model) + (1, T, d_model) broadcasts over batch dim.
        x = x + self.pe[:, : x.size(1), :]   # (B, T, d_model)
        return self.dropout(x)                # (B, T, d_model)


# ---------------------------------------------------------------------------
# ACT Transformer
# ---------------------------------------------------------------------------

class ACTTransformer(nn.Module):
    """Encoder-Decoder Transformer for action chunking (ACT-style).

    Takes a CNN feature vector and predicts chunk_size future action logits.

    Parameters
    ----------
    cnn_dim        : CNN backbone output dimension (e.g. 64 for 3-conv, 128 for 4-conv)
    d_model        : internal transformer dimension — all tokens are this wide
    nhead          : number of attention heads (d_model must be divisible by nhead)
    num_enc_layers : number of stacked TransformerEncoder layers
    num_dec_layers : number of stacked TransformerDecoder layers
    ff_dim         : feed-forward hidden dimension (typically 4× d_model)
    chunk_size     : how many future action steps to predict
    num_actions    : number of output actions (4: forward/backward/left/right)
    dropout        : dropout probability used throughout
    """

    def __init__(
        self,
        cnn_dim: int,
        d_model: int,
        nhead: int,
        num_enc_layers: int,
        num_dec_layers: int,
        ff_dim: int,
        chunk_size: int,
        num_actions: int,
        dropout: float = 0.1,
    ) -> None:
        super().__init__()

        # ── Input projection ──────────────────────────────────────────
        # The CNN produces a flat vector of cnn_dim numbers.
        # The Transformer expects tokens of d_model numbers.
        # This Linear layer re-sizes the CNN output to match.
        # Result: one d_model-dimensional token representing "what I see".
        # Shape transform: (B, cnn_dim) → (B, d_model)
        self.input_proj = nn.Linear(cnn_dim, d_model)

        # ── Positional encoding ───────────────────────────────────────
        # Applied to the encoder input (sequence of 1 token here) and
        # to the decoder query tokens (sequence of chunk_size tokens).
        self.pos_enc = PositionalEncoding(d_model, dropout=dropout)

        # ── Transformer Encoder ───────────────────────────────────────
        # Stacks num_enc_layers of:
        #   multi-head self-attention → add & norm → feed-forward → add & norm
        # Input:  (B, T, d_model) — here T=1 (one CNN token)
        # Output: (B, T, d_model) — enriched representation
        #
        # batch_first=True means input/output shape is (B, T, d_model).
        # The default (batch_first=False) uses (T, B, d_model) — confusing.
        # We always use batch_first=True to keep batch dim first, consistent
        # with every other tensor in this project.
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model,
            nhead=nhead,
            dim_feedforward=ff_dim,
            dropout=dropout,
            batch_first=True,   # (B, T, D) convention
        )
        self.encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_enc_layers)

        # ── Learnable query embeddings ────────────────────────────────
        # The decoder needs chunk_size queries — one per future action step.
        # nn.Embedding(chunk_size, d_model) gives us chunk_size learnable
        # d_model-dimensional vectors. These are NOT instruction IDs —
        # they are positional queries: "what should I do at step 0?",
        # "what at step 1?", etc.
        # Shape: (chunk_size, d_model) → will be expanded to (B, chunk_size, d_model)
        self.query_embed = nn.Embedding(chunk_size, d_model)

        # ── Transformer Decoder ───────────────────────────────────────
        # Stacks num_dec_layers of:
        #   self-attention on queries → add & norm
        #   cross-attention (Q=queries, K/V=encoder output) → add & norm
        #   feed-forward → add & norm
        # Input:  tgt (B, chunk_size, d_model)  — query tokens
        #         memory (B, T, d_model)         — encoder output
        # Output: (B, chunk_size, d_model)
        decoder_layer = nn.TransformerDecoderLayer(
            d_model=d_model,
            nhead=nhead,
            dim_feedforward=ff_dim,
            dropout=dropout,
            batch_first=True,   # (B, T, D) convention
        )
        self.decoder = nn.TransformerDecoder(decoder_layer, num_layers=num_dec_layers)

        # ── Action head ───────────────────────────────────────────────
        # Final linear layer: maps each d_model-dim decoder output token
        # to num_actions raw logits.
        # Shape: (B, chunk_size, d_model) → (B, chunk_size, num_actions)
        self.action_head = nn.Linear(d_model, num_actions)

        # Store chunk_size so forward() can build the query index tensor.
        self.chunk_size = chunk_size

    def forward(self, cnn_features: torch.Tensor) -> torch.Tensor:
        """
        Parameters
        ----------
        cnn_features : (B, cnn_dim)   — CNN backbone output

        Returns
        -------
        logits : (B, chunk_size, num_actions)   — raw action logits
                 logits[b, t, a] = score for action a at future step t in sample b
        """
        B = cnn_features.size(0)   # batch size — number of images in this batch

        # ── Step 1: Project CNN features to d_model ───────────────────
        # (B, cnn_dim) → (B, d_model)
        x = self.input_proj(cnn_features)   # (B, d_model)

        # The Transformer encoder expects a SEQUENCE of tokens, shape (B, T, d_model).
        # We have one token per image, so T=1.
        # unsqueeze(1) inserts a size-1 dimension at position 1.
        x = x.unsqueeze(1)   # (B, 1, d_model)

        # ── Step 2: Positional encoding on encoder input ──────────────
        # Adds position information to the (B, 1, d_model) token.
        # With only one token this is trivial, but the convention is
        # maintained for consistency and for cases where multiple encoder
        # tokens are used in future extensions.
        x = self.pos_enc(x)   # (B, 1, d_model)

        # ── Step 3: Transformer Encoder ───────────────────────────────
        # Self-attention over the encoder tokens (T=1 here → trivially
        # each token attends only to itself).
        # memory = encoded representation of the image input.
        memory = self.encoder(x)   # (B, 1, d_model)

        # ── Step 4: Build decoder queries ─────────────────────────────
        # Create integer indices [0, 1, 2, ..., chunk_size-1]
        # These are the IDs for the query_embed lookup table.
        # device must match the model's device.
        query_ids = torch.arange(self.chunk_size, device=cnn_features.device)
        # query_ids shape: (chunk_size,)

        # Look up the learnable embedding for each query position.
        # (chunk_size,) → (chunk_size, d_model)
        queries = self.query_embed(query_ids)   # (chunk_size, d_model)

        # Expand to batch dim so every sample in the batch gets the same
        # initial query embeddings (they will be differentiated by cross-attention).
        # unsqueeze(0) → (1, chunk_size, d_model)
        # expand(B, ...) → (B, chunk_size, d_model)   ← no new memory allocated
        queries = queries.unsqueeze(0).expand(B, -1, -1)   # (B, chunk_size, d_model)

        # ── Step 5: Positional encoding on decoder queries ────────────
        # Each query corresponds to a future time step.
        # Adding positional encoding lets the decoder distinguish
        # "what to do at step 0" from "what to do at step 7".
        queries = self.pos_enc(queries)   # (B, chunk_size, d_model)

        # ── Step 6: Transformer Decoder ───────────────────────────────
        # tgt    = queries    (B, chunk_size, d_model)  ← "what do I ask about?"
        # memory = encoder    (B, 1, d_model)           ← "what does the image say?"
        #
        # Internally the decoder does:
        #   1. self-attention on queries  → queries attend to each other
        #   2. cross-attention:
        #        Q = queries (B, chunk_size, d_model)
        #        K = memory  (B, 1, d_model)
        #        V = memory  (B, 1, d_model)
        #        scores = Q @ K^T → (B, chunk_size, 1)
        #        output = scores @ V → (B, chunk_size, d_model)
        #      Each future step query gathers relevant information from
        #      the encoder's image representation.
        #   3. feed-forward applied per token
        decoded = self.decoder(tgt=queries, memory=memory)   # (B, chunk_size, d_model)

        # ── Step 7: Action head ───────────────────────────────────────
        # Project each d_model-dim decoded token to num_actions logits.
        # Applied identically to every time step (same Linear layer, called
        # chunk_size times via batched matmul).
        # (B, chunk_size, d_model) → (B, chunk_size, num_actions)
        logits = self.action_head(decoded)   # (B, chunk_size, num_actions)

        return logits
